sudo: false
language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
env:
  - ANSIBLE=2.4
  - ANSIBLE=2.5
  - ANSIBLE=2.6
  - ANSIBLE=2.7
  - ANSIBLE=devel
matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true
  fast_finish: true
  allow_failures:
    - ANSIBLE=devel
install: pip install tox-travis
script:
  - tox
