sudo: false
language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
env:
  - ANSIBLE=2.7
  - ANSIBLE=2.8
  - ANSIBLE=2.9
matrix:
  include:
    - python: 3.8
      dist: xenial
      sudo: true
      env: ANSIBLE=2.7
    - python: 3.8
      dist: xenial
      sudo: true
      env: ANSIBLE=2.8
    - python: 3.8
      dist: xenial
      sudo: true
      env: ANSIBLE=2.9
  fast_finish: true
install: pip install tox-travis
script:
  - tox
